### ISSUE TITLE
Unable to execute MedusaGraph

### ISSUE THREAD

**Issue by Fr3nkM** [j9650/MedusaGraph#1]
I'm trying to run MedusaGraph on example data in the repository.
After the data dir creation, it give me the below error:

data dir created!
Traceback (most recent call last):
  File "/home/Medusa_dock/MedusaGraph-main/medusagraph.py", line 126, in <module>
    output_poses = generate_pose(data_dir, prediction_model, device)
  File "/home/Medusa_dock/MedusaGraph-main/medusagraph.py", line 52, in generate_pose
    out = model(data.x.to(device), data.edge_index.to(device), data.dist.to(device))[data.flexible_idx.bool()]
  File "/home/user/miniconda3/envs/Medusa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Medusa_dock/MedusaGraph-main/model.py", line 476, in forward
    x = self.conv1(x, edge_index, edge_attr)
  File "/home/user/miniconda3/envs/Medusa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/miniconda3/envs/Medusa/lib/python3.10/site-packages/torch_geometric/nn/conv/transformer_conv.py", line 176, in forward
    out = self.propagate(edge_index, query=query, key=key, value=value,
  File "/home/user/miniconda3/envs/Medusa/lib/python3.10/site-packages/torch_geometric/nn/conv/message_passing.py", line 263, in propagate
    decomposed_layers = 1 if self._explain else self.decomposed_layers
  File "/home/user/miniconda3/envs/Medusa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
**AttributeError: 'TransformerConv' object has no attribute '_explain'. Did you mean: '__explain__'?**

conda env python=3.10
torch-geometric=2.0.4

**Comment by j9650** [comment]
It looks like some of the attribute definition was change among different version of the packages.
I attched the version of the packages I used, please take a look:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
ase                       3.21.0b1                 pypi_0    pypi
attrs                     20.3.0             pyhd3eb1b0_0
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.12.8            h06a4308_0
certifi                   2020.12.5        py37h06a4308_0
cffi                      1.14.4           py37h261ae71_0
chardet                   4.0.0           py37h06a4308_1003
cmake                     3.18.2               ha30ef3c_0
cryptography              3.3.1            py37h3c74f83_0
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                   py37_0
dbus                      1.13.18              hb2f20db_0
decorator                 4.4.2                      py_0
expat                     2.2.10               he6710b0_2
fontconfig                2.13.0               h9420a91_0
freetype                  2.10.4               h5ab3b9f_0
glib                      2.66.1               h92f7085_0
googledrivedownloader     0.4                      pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb31296c_0
h5py                      2.10.0           py37hd6299e0_1
hdf5                      1.10.6               hb1b8bf9_0
icu                       58.2                 he6710b0_3
idna                      2.10                       py_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
iniconfig                 1.1.1                      py_0
intel-openmp              2020.2                      254
isodate                   0.6.0                      py_1
jinja2                    2.11.2                     py_0
joblib                    1.0.0              pyhd3eb1b0_0
jpeg                      9b                   h024ee3a_2
kiwisolver                1.3.0            py37h2531618_0
krb5                      1.18.2               h173b8e3_0
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libcurl                   7.71.1               h20c2e04_1
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libllvm10                 10.0.1               hbcb73fb_5
libpng                    1.6.37               hbc83047_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
libuuid                   1.0.3                h1bed415_2
libuv                     1.40.0               h7b6447c_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
llvmlite                  0.34.0           py37h269e1b5_4
lz4-c                     1.9.2                heb0550a_3
magma-cuda102             2.5.2                         1    pytorch
markupsafe                1.1.1            py37h14c3975_1
matplotlib                3.3.2                h06a4308_0
matplotlib-base           3.3.2            py37h817c723_0
mkl                       2020.2                      256
mkl-include               2020.2                      256
mkl-service               2.3.0            py37he8ac12f_0
mkl_fft                   1.2.0            py37h23d657b_0
mkl_random                1.1.1            py37h0573a6f_0
more-itertools            8.6.0              pyhd3eb1b0_0
ncurses                   6.2                  he6710b0_1
networkx                  2.5                        py_0
ninja                     1.10.2           py37hff7bd54_0
numba                     0.51.2           py37h04863e7_1
numpy                     1.19.2           py37h54aff64_0
numpy-base                1.19.2           py37hfa32c7d_0
olefile                   0.46                     py37_0
openssl                   1.1.1i               h27cfd23_0
packaging                 20.8               pyhd3eb1b0_0
pandas                    1.1.5            py37ha9443f7_0
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he6710b0_0
pillow                    8.0.1            py37he98fc37_0
pip                       20.3.3           py37h06a4308_0
pluggy                    0.13.1                   py37_0
py                        1.10.0             pyhd3eb1b0_0
pycparser                 2.20                       py_2
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h05f1152_2
pysocks                   1.7.1                    py37_1
pytest                    6.2.1            py37h06a4308_0
pytest-runner             5.2                        py_0
python                    3.7.9                h7579374_0
python-dateutil           2.8.1                      py_0
python-louvain            0.14                       py_0
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2020.4             pyhd3eb1b0_0
pyyaml                    5.3.1            py37h7b6447c_1
qt                        5.9.7                h5867ecd_1
rdflib                    5.0.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0
requests                  2.25.1             pyhd3eb1b0_0
rhash                     1.4.0                h1ba5d50_0
scikit-learn              0.23.2           py37h0573a6f_0
scipy                     1.5.2            py37h0b6359f_0
setuptools                51.0.0           py37h06a4308_2
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0           py37h06a4308_0
sqlite                    3.33.0               h62c20be_0
tbb                       2020.3               hfd86e86_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               hbc83047_0
toml                      0.10.1                     py_0
torch-cluster             1.5.8                    pypi_0    pypi
torch-geometric           1.6.3                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.8                    pypi_0    pypi
torchvision               0.8.2                py37_cu102    pytorch
tornado                   6.1              py37h27cfd23_0
tqdm                      4.54.1             pyhd3eb1b0_0
typing_extensions         3.7.4.3                    py_0
urllib3                   1.26.2             pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0

**Comment by sorenwacker** [comment]
I got the same error:

```
/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch_geometric/deprecation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
Traceback (most recent call last):
  File "/home/swacker/workspace/MedusaGraph/medusagraph.py", line 126, in <module>
    output_poses = generate_pose(data_dir, prediction_model, device)
  File "/home/swacker/workspace/MedusaGraph/medusagraph.py", line 52, in generate_pose
    out = model(data.x.to(device), data.edge_index.to(device), data.dist.to(device))[data.flexible_idx.bool()]
  File "/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/swacker/workspace/MedusaGraph/model.py", line 476, in forward
    x = self.conv1(x, edge_index, edge_attr)
  File "/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch_geometric/nn/conv/transformer_conv.py", line 176, in forward
    out = self.propagate(edge_index, query=query, key=key, value=value,
  File "/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch_geometric/nn/conv/message_passing.py", line 263, in propagate
    decomposed_layers = 1 if self._explain else self.decomposed_layers
  File "/home/swacker/miniconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TransformerConv' object has no attribute '_explain'. Did you mean: '__explain__'?
```

**Comment by mini-goel** [comment]
I am getting below error:

Traceback (most recent call last):
  File "medusagraph.py", line 8, in <module>
    from torch_geometric.data import DataLoader
  File "/data/datab/miniconda3/envs/torch/lib/python3.7/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/data/datab/miniconda3/envs/torch/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/data/datab/miniconda3/envs/torch/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/data/datab/miniconda3/envs/torch/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

conda env python=3.7
torch=1.7.1
cuda=10.1
torch-geometric=1.6.3
torch-scatter=2.0.7
torch-sparse=0.6.9
torch-cluster=1.5.9
torch-spline-conv=1.2.1

Tried different versions of torch-geometric but none seems to be working. Couldn't install CUDA10.2 as it doesnt support 
torchvision==0.8.2 torchaudio==0.7.2. Any clue on how to resolve this?

**Comment by Alam0421052080** [comment]
> molecules converted

How did you solve this problem? Thanks in advance for your reply.
